import { Poppins } from 'next/font/google';
import type { Metadata } from "next";
import 'remixicon/fonts/remixicon.css';
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";
import PublicPageHeader from '@/components/layout/PublicPageHeader';
import SidebarMenu from '@/components/layout/renter/SidebarMenu';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Renter Dashboard",
  description: "Generated by create next app",
};


export default function RenterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className={`${poppins.className} antialiased`}>
        <PublicPageHeader />

        <aside className="hidden lg:block fixed top-20 left-0 bottom-0 z-40 w-64 shadow-sm lg:w-80">
          <SidebarMenu />
        </aside>

        <main className="min-h-screen bg-[#E4E4E4]/30 pt-10 pb-6 pl-4 pr-4 lg:pr-5 lg:ml-80 lg:pl-5 lg:pb-8 lg:pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}
