import type { Metadata } from "next";
import 'remixicon/fonts/remixicon.css';
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";
import PageHeader from '@/components/public/PageHeader';
import SidebarMenu from '@/components/layout/renter/SidebarMenu';

export const metadata: Metadata = {
  title: "Renter Dashboard",
  description: "Generated by create next app",
};


export default function RenterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <PageHeader />
      <SidebarMenu />

      <main className="min-h-screen bg-[#E4E4E4]/30 pt-20 pb-6 px-4 md:px-6 lg:ml-64 xl:ml-72 lg:px-8 xl:px-10 lg:pb-8 lg:pt-24">
        {children}
      </main>
    </>
  );
}
