import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import 'remixicon/fonts/remixicon.css';
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";
import "./globals.css";
import { UserProvider } from "@/context/userContext";
import { EquipmentProvider } from "@/context/equipmentContext";
import { MostViewedEquipmentProvider } from "@/context/mostViewContext";
import { HighlyRatedEquipmentProvider } from "@/context/highlyRatedContext";
import { RecommendationsEquipmentProvider } from "@/context/recommendationsContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <UserProvider>
          <EquipmentProvider>
            <MostViewedEquipmentProvider>
              <HighlyRatedEquipmentProvider>
                <RecommendationsEquipmentProvider>
                  {children}
                </RecommendationsEquipmentProvider>
              </HighlyRatedEquipmentProvider>
            </MostViewedEquipmentProvider>
          </EquipmentProvider>
        </UserProvider>
        <Toaster />
      </body>
    </html>
  );
}
